/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.image.ImageObserver;
import java.text.AttributedCharacterIterator;
import sun.java2d.loops.DrawLine;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.util.*;

import Control.ShortestDisControl;
/**
 *
 * @author rames
 */
public class Shortast extends javax.swing.JFrame {
    //int mappath [] = {0,0,0,0,0,0,0,0};
    
    public Shortast() {
        initComponents();
    }
    ShortestDisControl obj = new ShortestDisControl();
    
    int[] playerpath; // Array which stores the player path
    int verticesCount = 0;
    int[][] newmap = {
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0} };
    
    Random ne = new Random();
    
    public void generateDistance(){
        for(int i = 0; i < newmap.length; i++){
            for(int s = 0; s < newmap[i].length; s++){
                if(i == s){
                    newmap[i][s] = 0;
                }
                else if(i < s){
                    newmap[i][s] = ne.nextInt(46) + 5;
                }
                else{
                    continue;
                }
            }
        }
    }
    
    public void playerPath(int vertice){
        if(verticesCount <= 9){
            playerpath[verticesCount] = vertice;
            verticesCount++;
        }
        else{
            // print a dialog box saying have reached choosing maximum vertices or something 
        }
    }
    
    public void calculateShortestDistance(){ //make this method to get call when use clicks the check button!
        obj.shortestDistnace(newmap);
        Integer[] playerPathInteger = Arrays.stream(playerpath).boxed().toArray(Integer[]::new);
        List<Integer> list = Arrays.asList(playerPathInteger);
        if(obj.checkPlayerAnswer(list) == true){
            // show answer is correct
        }
        else{
            // show answer is incorrect
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        map = new javax.swing.JPanel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_9 = new javax.swing.JButton();
        btn_close_window = new javax.swing.JButton();
        btn_generate_paths = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        distance_a_c = new javax.swing.JLabel();
        distance_c_e = new javax.swing.JLabel();
        distance_a_b = new javax.swing.JLabel();
        distance_a_d = new javax.swing.JLabel();
        distance_c_d = new javax.swing.JLabel();
        distance_d_f = new javax.swing.JLabel();
        distance_e_f = new javax.swing.JLabel();
        distance_d_e = new javax.swing.JLabel();
        distance_b_g = new javax.swing.JLabel();
        distance_b_d = new javax.swing.JLabel();
        distance_d_h = new javax.swing.JLabel();
        distance_i_f = new javax.swing.JLabel();
        distance_i_h = new javax.swing.JLabel();
        distance_b_h = new javax.swing.JLabel();
        distance_i_g = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 128, 19));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Find Shortast Path");

        map.setBackground(new java.awt.Color(255, 255, 255));

        btn_1.setBackground(new java.awt.Color(255, 255, 255));
        btn_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_1.setForeground(new java.awt.Color(0, 0, 0));
        btn_1.setText("City A");
        btn_1.setBorder(null);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(255, 255, 255));
        btn_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_2.setForeground(new java.awt.Color(0, 0, 0));
        btn_2.setText("City B");
        btn_2.setBorder(null);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/A.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/B.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/C.png"))); // NOI18N

        btn_3.setBackground(new java.awt.Color(255, 255, 255));
        btn_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_3.setForeground(new java.awt.Color(0, 0, 0));
        btn_3.setText("City C");
        btn_3.setBorder(null);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/D.png"))); // NOI18N

        btn_4.setBackground(new java.awt.Color(255, 255, 255));
        btn_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_4.setForeground(new java.awt.Color(0, 0, 0));
        btn_4.setText("City D");
        btn_4.setBorder(null);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/E.png"))); // NOI18N

        btn_5.setBackground(new java.awt.Color(255, 255, 255));
        btn_5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_5.setForeground(new java.awt.Color(0, 0, 0));
        btn_5.setText("City E");
        btn_5.setBorder(null);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(255, 255, 255));
        btn_6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_6.setForeground(new java.awt.Color(0, 0, 0));
        btn_6.setText("City F");
        btn_6.setBorder(null);
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/F.png"))); // NOI18N

        btn_7.setBackground(new java.awt.Color(255, 255, 255));
        btn_7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_7.setForeground(new java.awt.Color(0, 0, 0));
        btn_7.setText("City G");
        btn_7.setBorder(null);
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/G.png"))); // NOI18N

        btn_8.setBackground(new java.awt.Color(255, 255, 255));
        btn_8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_8.setForeground(new java.awt.Color(0, 0, 0));
        btn_8.setText("City H");
        btn_8.setBorder(null);
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/H.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/I.png"))); // NOI18N

        btn_9.setBackground(new java.awt.Color(255, 255, 255));
        btn_9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_9.setForeground(new java.awt.Color(0, 0, 0));
        btn_9.setText("City I");
        btn_9.setBorder(null);
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mapLayout = new javax.swing.GroupLayout(map);
        map.setLayout(mapLayout);
        mapLayout.setHorizontalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapLayout.createSequentialGroup()
                .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(296, 296, 296))
                    .addGroup(mapLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176)))
                .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(87, 87, 87))
            .addGroup(mapLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapLayout.createSequentialGroup()
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapLayout.createSequentialGroup()
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mapLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(189, 189, 189)))
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapLayout.createSequentialGroup()
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapLayout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(207, 207, 207))
                            .addGroup(mapLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(87, 87, 87)))
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapLayout.createSequentialGroup()
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mapLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))))
        );
        mapLayout.setVerticalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapLayout.createSequentialGroup()
                .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)))
                    .addGroup(mapLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mapLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))))
                .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mapLayout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4))
                            .addGroup(mapLayout.createSequentialGroup()
                                .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mapLayout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addGroup(mapLayout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mapLayout.createSequentialGroup()
                                .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(mapLayout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(45, 45, 45)
                        .addGroup(mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addContainerGap())))
        );

        btn_close_window.setBackground(new java.awt.Color(255, 128, 19));
        btn_close_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/close.png"))); // NOI18N
        btn_close_window.setBorder(null);
        btn_close_window.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_close_windowActionPerformed(evt);
            }
        });

        btn_generate_paths.setBackground(new java.awt.Color(255, 255, 255));
        btn_generate_paths.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_generate_paths.setForeground(new java.awt.Color(0, 0, 0));
        btn_generate_paths.setText("Generate All Possible Paths");
        btn_generate_paths.setBorder(null);
        btn_generate_paths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generate_pathsActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/system-solid-28-info (1).gif"))); // NOI18N
        jButton2.setText("Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(255, 51, 51));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(0, 0, 0));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/system-solid-18-autorenew (1).gif"))); // NOI18N
        btn_reset.setText("Restart");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/shortast.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        distance_a_c.setForeground(new java.awt.Color(0, 0, 0));
        distance_a_c.setText("Distance A - B : N/A");

        distance_c_e.setForeground(new java.awt.Color(0, 0, 0));
        distance_c_e.setText("N/A");

        distance_a_b.setForeground(new java.awt.Color(0, 0, 0));
        distance_a_b.setText("N/A");

        distance_a_d.setForeground(new java.awt.Color(0, 0, 0));
        distance_a_d.setText("N/A");

        distance_c_d.setForeground(new java.awt.Color(0, 0, 0));
        distance_c_d.setText("N/A");

        distance_d_f.setForeground(new java.awt.Color(0, 0, 0));
        distance_d_f.setText("N/A");

        distance_e_f.setForeground(new java.awt.Color(0, 0, 0));
        distance_e_f.setText("N/A");

        distance_d_e.setForeground(new java.awt.Color(0, 0, 0));
        distance_d_e.setText("N/A");

        distance_b_g.setForeground(new java.awt.Color(0, 0, 0));
        distance_b_g.setText("N/A");

        distance_b_d.setForeground(new java.awt.Color(0, 0, 0));
        distance_b_d.setText("N/A");

        distance_d_h.setForeground(new java.awt.Color(0, 0, 0));
        distance_d_h.setText("N/A");

        distance_i_f.setForeground(new java.awt.Color(0, 0, 0));
        distance_i_f.setText("N/A");

        distance_i_h.setForeground(new java.awt.Color(0, 0, 0));
        distance_i_h.setText("N/A");

        distance_b_h.setForeground(new java.awt.Color(0, 0, 0));
        distance_b_h.setText("N/A");

        distance_i_g.setForeground(new java.awt.Color(0, 0, 0));
        distance_i_g.setText("N/A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distance_i_g)
                    .addComponent(distance_b_h)
                    .addComponent(distance_i_h)
                    .addComponent(distance_i_f)
                    .addComponent(distance_d_h)
                    .addComponent(distance_b_d)
                    .addComponent(distance_b_g)
                    .addComponent(distance_d_e)
                    .addComponent(distance_e_f)
                    .addComponent(distance_d_f)
                    .addComponent(distance_c_d)
                    .addComponent(distance_a_d)
                    .addComponent(distance_a_b)
                    .addComponent(distance_c_e)
                    .addComponent(distance_a_c))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(distance_a_c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(distance_c_e)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(distance_a_b)
                .addGap(18, 18, 18)
                .addComponent(distance_a_d)
                .addGap(18, 18, 18)
                .addComponent(distance_c_d)
                .addGap(18, 18, 18)
                .addComponent(distance_d_f)
                .addGap(18, 18, 18)
                .addComponent(distance_e_f)
                .addGap(18, 18, 18)
                .addComponent(distance_d_e)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(distance_b_g)
                .addGap(18, 18, 18)
                .addComponent(distance_b_d)
                .addGap(18, 18, 18)
                .addComponent(distance_d_h)
                .addGap(18, 18, 18)
                .addComponent(distance_i_f)
                .addGap(18, 18, 18)
                .addComponent(distance_i_h)
                .addGap(18, 18, 18)
                .addComponent(distance_b_h)
                .addGap(18, 18, 18)
                .addComponent(distance_i_g)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_close_window, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(589, 589, 589)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_generate_paths, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(map, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(81, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btn_close_window, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btn_generate_paths, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(map, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        btn_2.setEnabled(false);
        
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_close_windowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_close_windowActionPerformed
        dispose();
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_btn_close_windowActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        btn_1.setEnabled(false);
        
        
        Graphics2D g2d = (Graphics2D)map.getGraphics();
        Stroke stk = new BasicStroke(3f);   //define thickness
        g2d.setStroke(stk);     //set thikness 
        g2d.setColor(new java.awt.Color(255, 128, 19));     //set color
        g2d.drawLine(btn_1.getLocation().x, btn_1.getLocation().y, btn_2.getLocation().x, btn_2.getLocation().y);   //set City A to City B path
        
        
        map.paintComponents(g2d);
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_generate_pathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generate_pathsActionPerformed
        // TODO add your handling code here:
        generateDistance();
        Graphics2D g2d = (Graphics2D)map.getGraphics();         //create map graphics
        
        g2d.drawLine(btn_1.getLocation().x, btn_1.getLocation().y, btn_2.getLocation().x, btn_2.getLocation().y);   //set City A to City B path
        g2d.drawLine(btn_1.getLocation().x, btn_1.getLocation().y, btn_3.getLocation().x, btn_3.getLocation().y);   //set City A to City C path
        g2d.drawLine(btn_1.getLocation().x, btn_1.getLocation().y, btn_4.getLocation().x, btn_4.getLocation().y);   //set City A to City D path
        g2d.drawLine(btn_3.getLocation().x, btn_3.getLocation().y, btn_4.getLocation().x, btn_4.getLocation().y);   //set City C to City D path
        g2d.drawLine(btn_2.getLocation().x, btn_2.getLocation().y, btn_4.getLocation().x, btn_4.getLocation().y);   //set City B to City D path
        g2d.drawLine(btn_4.getLocation().x, btn_4.getLocation().y, btn_5.getLocation().x, btn_5.getLocation().y);   //set City D to City E path
        g2d.drawLine(btn_3.getLocation().x, btn_3.getLocation().y, btn_5.getLocation().x, btn_5.getLocation().y);   //set City C to City E path
        g2d.drawLine(btn_6.getLocation().x, btn_6.getLocation().y, btn_5.getLocation().x, btn_5.getLocation().y);   //set City E to City F path
        g2d.drawLine(btn_6.getLocation().x, btn_6.getLocation().y, btn_4.getLocation().x, btn_4.getLocation().y);   //set City D to City F path
        g2d.drawLine(btn_2.getLocation().x, btn_2.getLocation().y, btn_7.getLocation().x, btn_7.getLocation().y);   //set City B to City G path
        g2d.drawLine(btn_2.getLocation().x, btn_2.getLocation().y, btn_8.getLocation().x, btn_8.getLocation().y);   //set City B to City H path
        g2d.drawLine(btn_6.getLocation().x, btn_6.getLocation().y, btn_9.getLocation().x, btn_9.getLocation().y);   //set City F to City I path
        g2d.drawLine(btn_4.getLocation().x, btn_4.getLocation().y, btn_8.getLocation().x, btn_8.getLocation().y);   //set City D to City H path
        g2d.drawLine(btn_9.getLocation().x, btn_9.getLocation().y, btn_8.getLocation().x, btn_8.getLocation().y);   //set City H to City I path
        g2d.drawLine(btn_9.getLocation().x, btn_9.getLocation().y, btn_7.getLocation().x, btn_7.getLocation().y);   //set City G to City I path
        
       
        
        distance_a_b.setText("Distance A - B : " + String.valueOf(newmap[0][1]));
        distance_a_c.setText("Distance A - C : " + String.valueOf(newmap[0][2]));
        distance_a_d.setText("Distance A - D : " + String.valueOf(newmap[0][3]));
        distance_b_d.setText("Distance B - D : " + String.valueOf(newmap[1][3]));
        distance_b_g.setText("Distance B - G : " + String.valueOf(newmap[1][6]));
        distance_b_h.setText("Distance B - H : " + String.valueOf(newmap[1][7]));
        distance_c_d.setText("Distance C - D : " + String.valueOf(newmap[2][3]));
        distance_c_e.setText("Distance C - E : " + String.valueOf(newmap[2][4]));
        distance_d_f.setText("Distance D - F : " + String.valueOf(newmap[3][5]));
        distance_d_h.setText("Distance D - H : " + String.valueOf(newmap[3][7]));
        distance_d_e.setText("Distance D - E : " + String.valueOf(newmap[3][4]));
        distance_e_f.setText("Distance E - F : " + String.valueOf(newmap[4][5]));
        distance_i_f.setText("Distance F - I : " + String.valueOf(newmap[5][8]));
        distance_i_g.setText("Distance G - I : " + String.valueOf(newmap[6][8]));
        distance_i_h.setText("Distance H - I : " + String.valueOf(newmap[7][8]));
        
         map.paintComponents(g2d);   //add drawings to map
    }//GEN-LAST:event_btn_generate_pathsActionPerformed

    public void activePath(int id){
        
    }
    
    
    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        btn_3.setEnabled(false);
        
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        btn_4.setEnabled(false);
        
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        btn_5.setEnabled(false);
        
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        btn_6.setEnabled(false);
        
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        btn_7.setEnabled(false);
        
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        btn_8.setEnabled(false);
        
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        btn_9.setEnabled(false);
        
    }//GEN-LAST:event_btn_9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Shortast sh = new Shortast();
        sh.setVisible(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shortast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shortast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shortast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shortast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shortast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_close_window;
    private javax.swing.JButton btn_generate_paths;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel distance_a_b;
    private javax.swing.JLabel distance_a_c;
    private javax.swing.JLabel distance_a_d;
    private javax.swing.JLabel distance_b_d;
    private javax.swing.JLabel distance_b_g;
    private javax.swing.JLabel distance_b_h;
    private javax.swing.JLabel distance_c_d;
    private javax.swing.JLabel distance_c_e;
    private javax.swing.JLabel distance_d_e;
    private javax.swing.JLabel distance_d_f;
    private javax.swing.JLabel distance_d_h;
    private javax.swing.JLabel distance_e_f;
    private javax.swing.JLabel distance_i_f;
    private javax.swing.JLabel distance_i_g;
    private javax.swing.JLabel distance_i_h;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel map;
    // End of variables declaration//GEN-END:variables
}
